name: Bixi Collector

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes
  workflow_dispatch:        # possibilité de lancer à la main aussi

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        run: python collect_bixi.py

      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: bixi-data
          path: bixi_realtime.csv
