name: Bixi Collector

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        run: python collect_bixi.py

      - name: Commit & Push CSV
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add bixi_realtime.csv
          git commit -m "Update Bixi CSV [skip ci]" || echo "No changes to commit"
          git push