name: Test Commit

on:
  workflow_dispatch:

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a test file
        run: echo "Hello from workflow" >> test.txt

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "macs1903"
          git config --global user.email "macs1903@users.noreply.github.com"
          git remote remove origin
          git remote add origin https://macs1903:${GH_PAT}@github.com/macs1903/bixi-data-collector.git
          git add test.txt
          git commit -m "Test commit [skip ci]" || echo "No changes"
          git push origin HEAD:main
