name: Test PAT Push

on:
  workflow_dispatch:  # pour le lancer manuellement

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy file
        run: echo "Test run at $(date)" > test.txt

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add test.txt
          git commit -m "Add test file [skip ci]" || echo "No changes"
          git push https://x-access-token:${GH_PAT}@github.com/macs1903/bixi-data-collector.git HEAD:main